#!/usr/bin/env python3
"""Merge Kahawai's Android manifest entries into the generated project.

The Android project (player/src-tauri/gen/android) is generated by
`cargo tauri android init` and gitignored, so manifest entries cannot be
committed there. This script idempotently adds what the generated manifest
lacks for background audio:

- FOREGROUND_SERVICE / FOREGROUND_SERVICE_MEDIA_PLAYBACK / WAKE_LOCK /
  POST_NOTIFICATIONS permissions (the service that keeps the Rust audio
  thread exempt from Doze throttling while playing)
- the PlaybackService declaration (player/src-tauri/android-overlay/...)
  with android:foregroundServiceType="mediaPlayback"

Run by scripts/build-android.sh and scripts/start-dev-android.sh after the
android-overlay copy. Safe to run repeatedly: entries already present are
left alone.

Usage: scripts/android-manifest-overlay.py [path-to-AndroidManifest.xml]
"""
import re
import sys
from pathlib import Path

PERMISSIONS = [
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK",
    "android.permission.WAKE_LOCK",
    # Runtime-requested on API 33+; declared so the request is legal there.
    "android.permission.POST_NOTIFICATIONS",
]

SERVICE_DECLARATION = """        <service
            android:name=".PlaybackService"
            android:foregroundServiceType="mediaPlayback"
            android:exported="false" />

"""


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    manifest = (
        Path(sys.argv[1])
        if len(sys.argv) > 1
        else root / "player/src-tauri/gen/android/app/src/main/AndroidManifest.xml"
    )
    if not manifest.is_file():
        print(f"android-manifest-overlay: no manifest at {manifest}, skipping")
        return 0

    text = manifest.read_text(encoding="utf-8")
    changed = False

    for permission in PERMISSIONS:
        if permission in text:
            continue
        anchor = '<uses-permission android:name="android.permission.INTERNET" />'
        entry = f'    <uses-permission android:name="{permission}" />\n'
        if anchor in text:
            text = text.replace(anchor, anchor + "\n" + entry.rstrip("\n"), 1)
        else:
            # Fall back to inserting before <application.
            text = text.replace("<application", entry + "    <application", 1)
        changed = True

    if "PlaybackService" not in text:
        closing = "    </application>"
        if closing in text:
            text = text.replace(closing, SERVICE_DECLARATION + closing, 1)
            changed = True

    # Sanity: the XML must still be well-formed.
    import xml.dom.minidom

    xml.dom.minidom.parseString(text)

    if changed:
        manifest.write_text(text, encoding="utf-8")
        print(f"android-manifest-overlay: updated {manifest}")
    else:
        print("android-manifest-overlay: manifest already has the entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
