#!/usr/bin/env python3
"""Generate the Android launcher icons from images/client-v2.png.

    python3 scripts/android-icons.py [source.png]

Writes into player/src-tauri/android-overlay/app/src/main/res (copied over the
generated, gitignored Android project by build-android.sh and
start-dev-android.sh):

- mipmap-*/ic_launcher_foreground.png  adaptive icon foreground (API 26+): the
  speaker sized to the launcher's safe zone, its glow running out to the mask
- mipmap-anydpi-v26/ic_launcher{,_round}.xml  the adaptive icon itself, on the
  dark background colour in values/ic_launcher_background.xml
- mipmap-*/ic_launcher.png, ic_launcher_round.png  legacy icons (before API 26,
  and launchers that ignore adaptive icons): the speaker on a dark rounded
  square / circle

Needs Pillow. The status-bar icon (drawable/ic_stat_kahawai.xml) is a vector
drawn by hand, not generated: Android shows it as a white silhouette.
"""

import sys
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
SOURCE = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "images/client-v2.png"
RES = ROOT / "player/src-tauri/android-overlay/app/src/main/res"

# Near-black, a touch blue, like the speaker's outer ring.
BACKGROUND = (11, 11, 14, 255)
BACKGROUND_HEX = "#0B0B0E"

# The speaker's dark outer ring spans this share of the 1024 px source; the
# rest is glow.
RING = 864 / 1024
# Adaptive foreground: the ring's diameter as a share of the 108 dp canvas.
# The launcher shows the middle 72 dp (any mask shape keeps a 66 dp circle),
# so the ring sits just inside that and the glow is cut by the mask.
FOREGROUND_RING = 0.60
# Legacy icons: the ring's share of the icon, glow around it.
LEGACY_RING = 0.80

# density: (legacy icon px, adaptive foreground px)
DENSITIES = {
    "mdpi": (48, 108),
    "hdpi": (72, 162),
    "xhdpi": (96, 216),
    "xxhdpi": (144, 324),
    "xxxhdpi": (192, 432),
}


def speaker(size: int, ring: float, src: Image.Image) -> Image.Image:
    """The source on a transparent `size` canvas, its ring `ring` of the width
    (`ring` < RING, so the whole source fits)."""
    drawn = round(size * ring / RING)
    canvas = Image.new("RGBA", (size, size))
    offset = (size - drawn) // 2
    canvas.alpha_composite(src.resize((drawn, drawn), Image.LANCZOS), (offset, offset))
    return canvas


def masked(size: int, src: Image.Image, shape: str) -> Image.Image:
    """The speaker on the dark background, cut to a rounded square or circle.
    Drawn at 4x and reduced, for smooth mask edges."""
    big = size * 4
    tile = Image.new("RGBA", (big, big), BACKGROUND)
    tile.alpha_composite(speaker(big, LEGACY_RING, src))
    mask = Image.new("L", (big, big))
    draw = ImageDraw.Draw(mask)
    if shape == "circle":
        draw.ellipse((0, 0, big - 1, big - 1), fill=255)
    else:
        draw.rounded_rectangle((0, 0, big - 1, big - 1), radius=big * 0.18, fill=255)
    out = Image.new("RGBA", (big, big))
    out.paste(tile, mask=mask)
    return out.resize((size, size), Image.LANCZOS)


ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/android-icons.py -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
"""

COLOR = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/android-icons.py -->
<resources>
    <color name="ic_launcher_background">{BACKGROUND_HEX}</color>
</resources>
"""


def main() -> None:
    src = Image.open(SOURCE).convert("RGBA")
    if src.size != (1024, 1024):
        src = src.resize((1024, 1024), Image.LANCZOS)
    for density, (legacy, foreground) in DENSITIES.items():
        folder = RES / f"mipmap-{density}"
        folder.mkdir(parents=True, exist_ok=True)
        speaker(foreground, FOREGROUND_RING, src).save(folder / "ic_launcher_foreground.png", optimize=True)
        masked(legacy, src, "square").save(folder / "ic_launcher.png", optimize=True)
        masked(legacy, src, "circle").save(folder / "ic_launcher_round.png", optimize=True)
    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        (anydpi / name).write_text(ADAPTIVE)
    (RES / "values").mkdir(parents=True, exist_ok=True)
    (RES / "values/ic_launcher_background.xml").write_text(COLOR)
    print(f"Android icons from {SOURCE.relative_to(ROOT) if SOURCE.is_relative_to(ROOT) else SOURCE} -> {RES.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
