//! Genre alias table (docs/v1/kahawai-genre-normalization-spec.md). Static
//! and meant to be extended: `GET /api/genres/report` lists the raw tags that
//! fell through to the keyword fallback or matched nothing.
//!
//! Keys are "squashed": lowercased, with everything but letters, digits and
//! `&` removed, so "Synth-pop", "Synth Pop" and "SynthPop" all read
//! `synthpop`. A key maps to one or more canonical genres, or to none for
//! values that aren't genres ("Other", "Unknown genre", "Various").

/// Whole-value aliases, tried first.
pub const ALIASES: &[(&str, &[&str])] = &[
    // --- not genres -------------------------------------------------------
    ("other", &[]),
    ("others", &[]),
    ("unknown", &[]),
    ("unknowngenre", &[]),
    ("undefined", &[]),
    ("none", &[]),
    ("null", &[]),
    ("nogenre", &[]),
    ("genre", &[]),
    ("default", &[]),
    ("misc", &[]),
    ("miscellaneous", &[]),
    ("various", &[]),
    ("variousartists", &[]),
    ("general", &[]),
    ("allgemein", &[]),
    ("divers", &[]),
    ("autres", &[]),
    ("onbekend", &[]),
    ("music", &[]),
    ("musik", &[]),
    ("remixes", &[]),
    ("remix", &[]),
    ("mashupremix", &[]),
    ("adulte", &[]),
    ("progressive", &[]),
    ("crossover", &[]),
    ("60s", &[]),
    ("70s", &[]),
    ("80s", &[]),
    ("90s", &[]),
    ("00s", &[]),
    // --- rock -------------------------------------------------------------
    ("rock", &["Rock"]),
    ("classicrock", &["Rock"]),
    ("softrock", &["Rock"]),
    ("slowrock", &["Rock"]),
    ("mainstreamrock", &["Rock"]),
    ("arenarock", &["Rock"]),
    ("pubrock", &["Rock"]),
    ("acousticrock", &["Rock"]),
    ("glamrock", &["Rock"]),
    ("artrock", &["Rock"]),
    ("avantrock", &["Rock", "Experimental"]),
    ("instrumentalrock", &["Rock"]),
    ("pianorock", &["Rock"]),
    ("garagerock", &["Rock"]),
    ("mathrock", &["Rock"]),
    ("postrock", &["Rock"]),
    ("celticrock", &["Rock", "Folk"]),
    ("poprock", &["Pop", "Rock"]),
    ("rockpop", &["Pop", "Rock"]),
    ("softrockpop", &["Pop", "Rock"]),
    ("folkrock", &["Folk", "Rock"]),
    ("countryrock", &["Country", "Rock"]),
    ("bluesrock", &["Blues", "Rock"]),
    ("dancerock", &["Dance", "Rock"]),
    ("hardrock", &["Hard Rock"]),
    ("rocknroll", &["Rock & Roll"]),
    ("rockandroll", &["Rock & Roll"]),
    ("rock&roll", &["Rock & Roll"]),
    ("rockabilly", &["Rock & Roll"]),
    ("rockabillyrevival", &["Rock & Roll"]),
    ("doowop", &["Rock & Roll"]),
    ("progressiverock", &["Progressive Rock"]),
    ("progrock", &["Progressive Rock"]),
    ("psychedelic", &["Psychedelic"]),
    ("psychadelic", &["Psychedelic"]),
    ("psychedelicrock", &["Psychedelic"]),
    ("psychedelicfolk", &["Psychedelic", "Folk"]),
    ("grunge", &["Grunge"]),
    ("postgrunge", &["Grunge"]),
    // --- alternative / indie ---------------------------------------------
    ("alternative", &["Alternative"]),
    ("alternativerock", &["Alternative"]),
    ("alternatif", &["Alternative"]),
    ("alternativa", &["Alternative"]),
    ("altrock", &["Alternative"]),
    ("alt", &["Alternative"]),
    ("altpop", &["Alternative", "Pop"]),
    ("collegerock", &["Alternative"]),
    ("adultalternative", &["Alternative"]),
    ("adultalternativepop", &["Alternative", "Pop"]),
    ("generaladultalternativerock", &["Alternative"]),
    ("opmalternative", &["Alternative"]),
    ("alternativepop", &["Alternative", "Pop"]),
    ("popalternative", &["Alternative", "Pop"]),
    ("shoegaze", &["Alternative"]),
    ("dreampop", &["Alternative", "Pop"]),
    ("alternativepunk", &["Alternative", "Punk"]),
    ("alternative&punk", &["Alternative", "Punk"]),
    ("alternativemetal", &["Alternative", "Metal"]),
    ("alternativedance", &["Alternative", "Dance"]),
    ("alternative&indie", &["Alternative", "Indie"]),
    ("alternativeindie", &["Alternative", "Indie"]),
    ("alternativaeindie", &["Alternative", "Indie"]),
    ("alternatifetindé", &["Alternative", "Indie"]),
    ("indie", &["Indie"]),
    ("indierock", &["Indie", "Rock"]),
    ("indiepop", &["Indie", "Pop"]),
    ("indiуpop", &["Indie", "Pop"]),
    ("indiefolk", &["Indie", "Folk"]),
    // --- punk, post-punk, new wave, goth, metal ----------------------------
    ("punk", &["Punk"]),
    ("punkrock", &["Punk"]),
    ("hardcorepunk", &["Punk"]),
    ("poppunk", &["Punk"]),
    ("newyorkpunk", &["Punk"]),
    ("artpunk", &["Punk"]),
    ("posthardcore", &["Punk"]),
    ("punk&newwave", &["Punk", "New Wave"]),
    ("postpunk", &["Post-Punk"]),
    ("newwave", &["New Wave"]),
    ("newromantic", &["New Wave"]),
    ("minimalsynth", &["New Wave"]),
    ("gothic", &["Gothic"]),
    ("ghotic", &["Gothic"]),
    ("gothicrock", &["Gothic"]),
    ("gothrock", &["Gothic"]),
    ("darkwave", &["Gothic"]),
    ("metal", &["Metal"]),
    ("heavymetal", &["Metal"]),
    ("thrashmetal", &["Metal"]),
    ("progressivemetal", &["Metal"]),
    ("crossoverthrash", &["Metal"]),
    // --- pop ----------------------------------------------------------------
    ("pop", &["Pop"]),
    ("popular", &["Pop"]),
    ("europop", &["Pop"]),
    ("internationalpop", &["Pop"]),
    ("adultcontemporary", &["Pop"]),
    ("ballad", &["Pop"]),
    ("powerpop", &["Pop"]),
    ("noisepop", &["Pop"]),
    ("trashypop", &["Pop"]),
    ("britpop", &["Pop", "Rock"]),
    ("baroquepop", &["Pop"]),
    ("dancepop", &["Dance", "Pop"]),
    ("popsoul", &["Pop", "Soul"]),
    ("popeasylistening", &["Pop", "Easy Listening"]),
    ("oldies", &["Pop"]),
    ("opm", &["Pop"]),
    ("chanson", &["Pop"]),
    ("chansonfrançaise", &["Pop"]),
    ("jpop", &["J-Pop"]),
    ("kpop", &["K-Pop"]),
    ("citypop", &["J-Pop"]),
    ("synthpop", &["Synth-Pop"]),
    ("synthiepop", &["Synth-Pop"]),
    ("electropop", &["Synth-Pop"]),
    ("synth", &["Synth-Pop"]),
    ("singersongwriter", &["Singer-Songwriter"]),
    ("singer&songwriter", &["Singer-Songwriter"]),
    // "Singer/Songwriter" splits on the slash.
    ("singer", &["Singer-Songwriter"]),
    ("songwriter", &["Singer-Songwriter"]),
    ("авторыисполнители", &["Singer-Songwriter"]),
    // --- hip-hop, r&b, soul, funk, disco ------------------------------------
    ("hiphop", &["Hip-Hop"]),
    ("rap", &["Hip-Hop"]),
    ("hiphoprap", &["Hip-Hop"]),
    ("poprap", &["Hip-Hop"]),
    ("instrumentalhiphop", &["Hip-Hop"]),
    ("chillhop", &["Hip-Hop"]),
    ("r&b", &["R&B"]),
    ("rnb", &["R&B"]),
    ("rhythm&blues", &["R&B"]),
    ("rhythmandblues", &["R&B"]),
    ("contemporaryr&b", &["R&B"]),
    ("quietstorm", &["R&B"]),
    ("soul", &["Soul"]),
    ("neosoul", &["Soul"]),
    ("blueeyedsoul", &["Soul"]),
    ("smoothsoul", &["Soul"]),
    ("motown", &["Soul"]),
    ("soulr&bfunk", &["Soul", "R&B", "Funk"]),
    ("soul&funk", &["Soul", "Funk"]),
    ("funk&soul", &["Soul", "Funk"]),
    ("souljazz", &["Soul", "Jazz"]),
    ("funk", &["Funk"]),
    ("funky", &["Funk"]),
    ("jazzfunk", &["Jazz", "Funk"]),
    ("disco", &["Disco"]),
    ("nudisco", &["Disco"]),
    ("italodisco", &["Disco"]),
    // --- jazz, blues ----------------------------------------------------------
    ("jazz", &["Jazz"]),
    ("jazzy", &["Jazz"]),
    ("avantgardejazz", &["Jazz", "Experimental"]),
    ("hardbop", &["Jazz"]),
    ("bebop", &["Jazz"]),
    ("bebob", &["Jazz"]),
    ("bop", &["Jazz"]),
    ("postbop", &["Jazz"]),
    ("jazzpostbop", &["Jazz"]),
    ("modal", &["Jazz"]),
    ("cooljazz", &["Jazz"]),
    ("vocaljazz", &["Jazz"]),
    ("jazzvocal", &["Jazz"]),
    ("contemporaryjazz", &["Jazz"]),
    ("jazzcontemporain", &["Jazz"]),
    ("freejazz", &["Jazz"]),
    ("gypsyjazz", &["Jazz"]),
    ("mainstreamjazz", &["Jazz"]),
    ("classicjazz", &["Jazz"]),
    ("pianojazz", &["Jazz"]),
    ("orchestraljazz", &["Jazz"]),
    ("instrumentaljazz", &["Jazz"]),
    ("jazzinstrumental", &["Jazz"]),
    ("instrumentalejazz", &["Jazz"]),
    ("swing", &["Jazz"]),
    ("dixieland", &["Jazz"]),
    ("traditional", &["Jazz"]),
    ("bigband", &["Jazz"]),
    ("acidjazz", &["Jazz"]),
    ("nujazz", &["Jazz"]),
    ("futurejazz", &["Jazz"]),
    ("jazzlounge", &["Jazz", "Lounge"]),
    ("latinjazz", &["Jazz", "Latin"]),
    ("afrocubanjazz", &["Jazz", "Latin"]),
    ("jazzblues", &["Jazz", "Blues"]),
    ("smoothjazz", &["Smooth Jazz"]),
    ("smoothjazzinstrumental", &["Smooth Jazz"]),
    ("jazzfusion", &["Jazz Fusion"]),
    ("fusion", &["Jazz Fusion"]),
    ("jazzrock", &["Jazz Fusion"]),
    ("jazzcrossover", &["Jazz Fusion"]),
    ("acousticfusion", &["Jazz Fusion"]),
    ("blues", &["Blues"]),
    ("deltablues", &["Blues"]),
    ("boogiewoogie", &["Blues"]),
    // --- country, folk ----------------------------------------------------------
    ("country", &["Country"]),
    ("americana", &["Country"]),
    ("countrypop", &["Country", "Pop"]),
    ("folk", &["Folk"]),
    ("folkpop", &["Folk", "Pop"]),
    ("celtic", &["Folk"]),
    ("filk", &["Folk"]),
    // --- classical -------------------------------------------------------------
    ("classical", &["Classical"]),
    ("classic", &["Classical"]),
    ("klassiek", &["Classical"]),
    ("klassik", &["Classical"]),
    ("classica", &["Classical"]),
    ("classique", &["Classical"]),
    ("musicaclassica", &["Classical"]),
    ("generalclassical", &["Classical"]),
    ("modernclassical", &["Classical"]),
    ("classicalguitar", &["Classical"]),
    ("spanishclassicalguitar", &["Classical"]),
    ("classicalspain", &["Classical"]),
    ("chambermusic", &["Classical"]),
    ("concerto", &["Classical"]),
    ("romanticism", &["Classical"]),
    ("orchestral", &["Classical"]),
    ("flötenquartett", &["Classical"]),
    ("streichquintett", &["Classical"]),
    ("indianclassical", &["Classical", "World"]),
    ("baroque", &["Baroque"]),
    ("opera", &["Opera"]),
    // --- electronic ---------------------------------------------------------------
    ("electronic", &["Electronic"]),
    ("electronica", &["Electronic"]),
    ("electro", &["Electronic"]),
    ("électronique", &["Electronic"]),
    ("elettronica", &["Electronic"]),
    ("электроннаямузыка", &["Electronic"]),
    ("electronicagrandpublic", &["Electronic"]),
    ("elettronicapop", &["Electronic", "Pop"]),
    ("popelettronica", &["Electronic", "Pop"]),
    ("edm", &["Electronic", "Dance"]),
    ("idm", &["Electronic"]),
    ("glitch", &["Electronic"]),
    ("bass", &["Electronic"]),
    ("leftfield", &["Electronic"]),
    ("abstract", &["Electronic"]),
    ("lofi", &["Electronic"]),
    ("synthwave", &["Electronic"]),
    ("chillwave", &["Electronic"]),
    ("progressiveelectro", &["Electronic"]),
    ("ebm", &["Electronic", "Industrial"]),
    ("house", &["House"]),
    ("deephouse", &["House"]),
    ("depphouse", &["House"]),
    ("techhouse", &["House"]),
    ("progressivehouse", &["House"]),
    ("acidhouse", &["House"]),
    ("electrohouse", &["House"]),
    ("eurohouse", &["House"]),
    ("soulfulhouse", &["House"]),
    ("funkyhouse", &["House"]),
    ("clubhouse", &["House"]),
    ("tribalhouse", &["House"]),
    ("ukgarage", &["House"]),
    ("chillhouse", &["House", "Chillout"]),
    ("loungehouse", &["House", "Lounge"]),
    ("melodichouse&techno", &["House", "Techno"]),
    ("techno", &["Techno"]),
    ("minimal", &["Techno"]),
    ("technoambient", &["Techno", "Ambient"]),
    ("trance", &["Trance"]),
    ("progressivetrance", &["Trance"]),
    ("techtrance", &["Trance"]),
    ("hardtrance", &["Trance"]),
    ("upliftingtrance", &["Trance"]),
    ("psytrance", &["Trance"]),
    ("acid", &["Trance"]),
    ("ambienttrance", &["Trance", "Ambient"]),
    ("ambient", &["Ambient"]),
    ("ambience", &["Ambient"]),
    ("psybient", &["Ambient"]),
    ("darkambient", &["Ambient"]),
    ("downtempo", &["Downtempo"]),
    ("lounge", &["Lounge"]),
    ("chillout", &["Chillout"]),
    ("chilout", &["Chillout"]),
    ("chill", &["Chillout"]),
    ("balearic", &["Chillout"]),
    ("triphop", &["Trip-Hop"]),
    ("breakbeat", &["Breakbeat"]),
    ("breaks", &["Breakbeat"]),
    ("bigbeat", &["Breakbeat"]),
    ("brokenbeat", &["Breakbeat"]),
    ("drum&bass", &["Drum & Bass"]),
    ("drumandbass", &["Drum & Bass"]),
    ("drumnbass", &["Drum & Bass"]),
    ("dnb", &["Drum & Bass"]),
    ("jungle", &["Drum & Bass"]),
    ("dubstep", &["Electronic"]),
    ("dance", &["Dance"]),
    ("club", &["Dance"]),
    ("danceclub", &["Dance"]),
    ("clubdance", &["Dance"]),
    ("dance&dj", &["Dance"]),
    ("dance&house", &["Dance", "House"]),
    ("танцевальнаямузыка", &["Dance"]),
    ("industrial", &["Industrial"]),
    ("experimental", &["Experimental"]),
    ("avantgarde", &["Experimental"]),
    ("noise", &["Experimental"]),
    ("newage", &["New Age"]),
    ("easylistening", &["Easy Listening"]),
    ("lightmusic", &["Easy Listening"]),
    // --- reggae, latin, world ---------------------------------------------------
    ("reggae", &["Reggae"]),
    ("rootsreggae", &["Reggae"]),
    ("loversrock", &["Reggae"]),
    ("dub", &["Reggae"]),
    ("ska", &["Ska"]),
    ("skarevival", &["Ska"]),
    ("latin", &["Latin"]),
    ("latinmusic", &["Latin"]),
    ("latijnsemuziek", &["Latin"]),
    ("latinpop", &["Latin", "Pop"]),
    ("amériquelatine", &["Latin"]),
    ("salsa", &["Latin"]),
    ("cubasalsa", &["Latin"]),
    ("samba", &["Latin"]),
    ("cumbia", &["Latin"]),
    ("mambo", &["Latin"]),
    ("rumba", &["Latin"]),
    ("guajira", &["Latin"]),
    ("pagode", &["Latin"]),
    ("mpb", &["Latin"]),
    ("brasileira", &["Latin"]),
    ("brazilianmusic", &["Latin"]),
    ("braziliaansemuziek", &["Latin"]),
    ("brésil", &["Latin"]),
    ("bossanova", &["Bossa Nova"]),
    ("bossanovalounge", &["Bossa Nova", "Lounge"]),
    ("flamenco", &["Flamenco"]),
    ("nuevoflamenco", &["Flamenco"]),
    ("flamencofusión", &["Flamenco"]),
    ("world", &["World"]),
    ("worldmusic", &["World"]),
    ("ethnic", &["World"]),
    ("musiquesdumonde", &["World"]),
    ("afroportugese", &["World"]),
    ("african", &["World"]),
    ("raï", &["World"]),
    ("bhangra", &["World"]),
    ("fado", &["World"]),
    ("zouk", &["World"]),
    ("calypso", &["World"]),
    // A world-music label that taggers use as a genre.
    ("putumayo", &["World"]),
    // --- soundtrack, stage -------------------------------------------------------
    ("soundtrack", &["Soundtrack"]),
    ("soundtracks", &["Soundtrack"]),
    ("score", &["Soundtrack"]),
    ("filmscores", &["Soundtrack"]),
    ("filmscore", &["Soundtrack"]),
    ("filmsoundtrack", &["Soundtrack"]),
    ("originalsoundtrack", &["Soundtrack"]),
    ("ost", &["Soundtrack"]),
    ("bso", &["Soundtrack"]),
    ("bandasonora", &["Soundtrack"]),
    ("bandesoriginalesdefilms", &["Soundtrack"]),
    ("film", &["Soundtrack"]),
    ("films", &["Soundtrack"]),
    ("games", &["Soundtrack"]),
    ("videogames", &["Soundtrack"]),
    ("videogiochi", &["Soundtrack"]),
    ("ghibli", &["Soundtrack"]),
    ("anime", &["Soundtrack"]),
    ("stage&screen", &["Soundtrack", "Musical"]),
    ("musical", &["Musical"]),
    ("musicals", &["Musical"]),
    ("showtunes", &["Musical"]),
    ("cabaret", &["Musical"]),
    // --- descriptors kept as genres ----------------------------------------------
    ("instrumental", &["Instrumental"]),
    ("piano", &["Instrumental"]),
    ("guitar", &["Instrumental"]),
    ("keyboard", &["Instrumental"]),
    ("vocal", &["Vocal"]),
    ("acappella", &["Vocal"]),
    ("musicavocale", &["Vocal"]),
    ("acoustic", &["Acoustic"]),
    ("spokenword", &["Spoken Word"]),
    ("podcast", &["Spoken Word"]),
    ("nonmusic", &["Spoken Word"]),
    ("comedy", &["Spoken Word"]),
    ("komedie", &["Spoken Word"]),
    ("childrens", &["Children's"]),
    ("children", &["Children's"]),
    ("kids", &["Children's"]),
    ("holiday", &["Holiday"]),
    ("christmas", &["Holiday"]),
    ("christmasmusic", &["Holiday"]),
    ("gospel", &["Gospel"]),
];

/// Genre words for values no alias covers ("Pinoy Rock", "Uplifting
/// Trance"). Matched against single words and adjacent word pairs, squashed
/// the same way as alias keys. Deliberately only unambiguous roots: "classic"
/// isn't here ("Classic Jazz" is jazz), nor "progressive" or "orchestral".
pub const KEYWORDS: &[(&str, &str)] = &[
    ("rock", "Rock"),
    ("pop", "Pop"),
    ("punk", "Punk"),
    ("postpunk", "Post-Punk"),
    ("newwave", "New Wave"),
    ("metal", "Metal"),
    ("grunge", "Grunge"),
    ("gothic", "Gothic"),
    ("jazz", "Jazz"),
    ("swing", "Jazz"),
    ("blues", "Blues"),
    ("soul", "Soul"),
    ("funk", "Funk"),
    ("disco", "Disco"),
    ("hiphop", "Hip-Hop"),
    ("rap", "Hip-Hop"),
    ("r&b", "R&B"),
    ("synthpop", "Synth-Pop"),
    ("electronic", "Electronic"),
    ("electronica", "Electronic"),
    ("electro", "Electronic"),
    ("house", "House"),
    ("techno", "Techno"),
    ("trance", "Trance"),
    ("ambient", "Ambient"),
    ("downtempo", "Downtempo"),
    ("lounge", "Lounge"),
    ("chillout", "Chillout"),
    ("triphop", "Trip-Hop"),
    ("breakbeat", "Breakbeat"),
    ("dance", "Dance"),
    ("folk", "Folk"),
    ("country", "Country"),
    ("classical", "Classical"),
    ("baroque", "Baroque"),
    ("opera", "Opera"),
    ("reggae", "Reggae"),
    ("ska", "Ska"),
    ("latin", "Latin"),
    ("salsa", "Latin"),
    ("samba", "Latin"),
    ("flamenco", "Flamenco"),
    ("soundtrack", "Soundtrack"),
    ("gospel", "Gospel"),
    ("industrial", "Industrial"),
    ("experimental", "Experimental"),
    ("christmas", "Holiday"),
];
